[M1S05] Ex. 01 - Leitura e Estruturação dos Dados (Pandas)

Importe os arquivos clientes.csv, pedidos.csv e produtos.csv usando Pandas. Explore os dados para entender sua estrutura.

In [4]:
#import da biblioteca
import pandas as pd #Onde pd é o alias (apelido)

In [5]:
#Leitura e armazenamento dos arquivos em DataFrames

df_clientes = pd.read_csv('clientes.csv')
df_pedidos = pd.read_csv('pedidos.csv')
df_produtos = pd.read_csv('produtos.csv')

#explorar as primeiras linhas de cada df
dfs_ativos = [
    ('clientes',df_clientes),
    ('pedidos',df_pedidos),
    ('produtos',df_produtos)
]

for nome, df in dfs_ativos:
    print(f"Primeiras 4 linhas do df {nome}:")
    print(df.head(4))
    print('\n')


#verificar tipos e nulos
for nome, df in dfs_ativos:
    print(f"Verificação de tipo e nulos do df {nome}")
    print(df.info())
    print(df.isnull().sum())
    print('\n')

#obter estatísticas de cada df
for nome, df in dfs_ativos:
    print(f"Estatísticas base do df {nome}")
    print(df.describe())
    print('\n')

Primeiras 4 linhas do df clientes:
   id_cliente           nome  idade          cidade
0           1      Ana Souza     28       Fortaleza
1           2    Carlos Lima     35          Recife
2           3  Mariana Alves     42        Salvador
3           4   João Pereira     31  Belo Horizonte


Primeiras 4 linhas do df pedidos:
   id_pedido  id_cliente data_pedido  valor_total
0        101           1  2025-09-01        320.5
1        102           2  2025-09-03        780.0
2        103           3  2025-09-05        150.0
3        104           4  2025-09-07        540.9


Primeiras 4 linhas do df produtos:
   id_produto            nome    categoria   preco
0         201  Fone Bluetooth  Eletrônicos   199.9
1         202  Notebook Gamer  Eletrônicos  4999.0
2         203    Livro Python       Livros    89.9
3         204   Cadeira Gamer       Móveis   799.0


Verificação de tipo e nulos do df clientes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  10 non-null     int64
 1   nome        10 non-null     object
 2   idade       10 non-null     int64
 3   cidade      10 non-null     object
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes
None
id_cliente    0
nome          0
idade         0
cidade        0
dtype: int64


Verificação de tipo e nulos do df pedidos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_pedido    10 non-null     int64
 1   id_cliente   10 non-null     int64
 2   data_pedido  10 non-null     object
 3   valor_total  10 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 448.0+ bytes
None
id_pedido      0
id_cliente     0
data_pedido    0
valor_total    0
dtype: int64


Verificação de tipo e nulos do df produtos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_produto  10 non-null     int64
 1   nome        10 non-null     object
 2   categoria   10 non-null     object
 3   preco       10 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes
None
id_produto    0
nome          0
categoria     0
preco         0
dtype: int64


Estatísticas base do df clientes
       id_cliente      idade
count    10.00000  10.000000
mean      5.50000  33.300000
std       3.02765   6.650814
min       1.00000  25.000000
25%       3.25000  28.250000
50%       5.50000  32.000000
75%       7.75000  37.250000
max      10.00000  45.000000


Estatísticas base do df pedidos
       id_pedido  id_cliente  valor_total
count   10.00000    10.00000     10.00000
mean   105.50000     5.50000    508.14000
std      3.02765     3.02765    364.60488
min    101.00000     1.00000    150.00000
25%    103.25000     3.25000    242.50000
50%    105.50000     5.50000    375.25000
75%    107.75000     7.75000    720.22500
max    110.00000    10.00000   1200.00000


Estatísticas base do df produtos
       id_produto        preco
count    10.00000    10.000000
mean    205.50000   974.630000
std       3.02765  1677.374824
min     201.00000    39.900000
25%     203.25000    82.400000
50%     205.50000   164.900000
75%     207.75000   686.725000
max     210.00000  4999.000000

[M1S05] Ex. 02 - Filtros e Seleções
Aplique filtros para extrair informações específicas dos DataFrames.

In [6]:
#filtrar dfs de acordo com as especificações
df_clientes_filtrado = df_clientes[df_clientes['idade'] > 30]
df_pedidos_filtrado = df_pedidos[df_pedidos['valor_total']>500]
df_produtos_filtrado = df_produtos[df_produtos['categoria']=='Eletrônicos']

#exemplos selecoes com iloc e loc

print('selecionar coluna inteira de data de df_pedidos_filtrado')
print(df_pedidos_filtrado.loc[:,'data_pedido'])
print('\n')

print('selecionar segunda linha inteira em df_produtos_filtrado')
print(df_produtos_filtrado.iloc[1,:])

selecionar coluna inteira de data de df_pedidos_filtrado
1    2025-09-03
3    2025-09-07
5    2025-09-12
7    2025-09-18
Name: data_pedido, dtype: object


selecionar segunda linha inteira em df_produtos_filtrado
id_produto               202
nome          Notebook Gamer
categoria        Eletrônicos
preco                 4999.0
Name: 1, dtype: object

[M1S05] Ex. 03 - Operações com Dataframes
Realize operações para cruzar e resumir os dados.

In [7]:
#juntar clientes e pedidos
df_merged = df_pedidos.merge(df_clientes,on='id_cliente')

#agrupar por clientes e somar valores
df_agrupado = df_merged.groupby(['id_cliente','nome'])['valor_total'].sum()
df_agrupado

id_cliente  nome
1           Ana Souza           320.5
2           Carlos Lima         780.0
3           Mariana Alves       150.0
4           João Pereira        540.9
5           Luciana Costa       220.0
6           Rafael Mendes       980.0
7           Beatriz Rocha       430.0
8           Felipe Martins     1200.0
9           Juliana Silva       310.0
10          Daniel Oliveira     150.0
Name: valor_total, dtype: float64

In [8]:
#exibir df_produtos para facilitar o proximo passo
df_produtos

   id_produto                  nome    categoria   preco
0         201        Fone Bluetooth  Eletrônicos   199.9
1         202        Notebook Gamer  Eletrônicos  4999.0
2         203          Livro Python       Livros    89.9
3         204         Cadeira Gamer       Móveis   799.0
4         205            Smartphone  Eletrônicos  2999.0
5         206         Luminária LED       Móveis   129.9
6         207          Mouse Óptico  Eletrônicos    79.9
7         208  Caneca Personalizada   Utilidades    39.9
8         209      Teclado Mecânico  Eletrônicos   349.9
9         210          Planner 2025    Papelaria    59.9

In [9]:
#criar tabela dinamica com categorias e medias de preços
tabdim = pd.pivot_table(df_produtos,values='preco',index='categoria',aggfunc='mean',margins=True)
tabdim

               preco
categoria
Eletrônicos  1725.54
Livros         89.90
Móveis        464.45
Papelaria      59.90
Utilidades     39.90
All           974.63

In [10]:
#verificar duplicatas
df_pedidos.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [11]:
#limpar duplicatas (caso fosse necessario)
df_pedidos = df_pedidos.drop_duplicates()

[M1S05] Ex. 04 - Análise Numérica com NumPy

Utilize NumPy para cálculos e simulações com arrays.

In [29]:
#importar numpy
import numpy as np

#criar array com valores dos pedidos
array_pedidos = np.array(df_pedidos['valor_total'])

print("Array criado: ",array_pedidos,'\n')

#calcular média, soma, desvio padrão
print('Média: ',array_pedidos.mean())
print('Soma: ',array_pedidos.sum())
print('Desvio Padrão',array_pedidos.std())
print('\n')

#Aplicar Desconto de 10% com broadcasting
array_pedidos_com_desconto = array_pedidos * 0.9
print("Array com desconto de 10%: ",array_pedidos_com_desconto)
print('\n')

#Verificar tipos e dimensões com .dtype() e .shape()
print('Dtype: ',array_pedidos.dtype)
print('Shape: ',array_pedidos.shape)

Array criado:  [ 320.5  780.   150.   540.9  220.   980.   430.  1200.   310.   150. ]

Média:  508.14
Soma:  5081.4
Desvio Padrão 345.89455965655196


Array com desconto de 10%:  [ 288.45  702.    135.    486.81  198.    882.    387.   1080.    279.
  135.  ]


Dtype:  float64
Shape:  (10,)